(** Values of physical constants *)

val cgsm_speed_of_light : float
val cgsm_gravitational_constant : float
val cgsm_plancks_constant_h : float
val cgsm_plancks_constant_hbar : float
val cgsm_astronomical_unit : float
val cgsm_light_year : float
val cgsm_parsec : float
val cgsm_grav_accel : float
val cgsm_electron_volt : float
val cgsm_mass_electron : float
val cgsm_mass_muon : float
val cgsm_mass_proton : float
val cgsm_mass_neutron : float
val cgsm_rydberg : float
val cgsm_boltzmann : float
val cgsm_molar_gas : float
val cgsm_standard_gas_volume : float
val cgsm_minute : float
val cgsm_hour : float
val cgsm_day : float
val cgsm_week : float
val cgsm_inch : float
val cgsm_foot : float
val cgsm_yard : float
val cgsm_mile : float
val cgsm_nautical_mile : float
val cgsm_fathom : float
val cgsm_mil : float
val cgsm_point : float
val cgsm_texpoint : float
val cgsm_micron : float
val cgsm_angstrom : float
val cgsm_hectare : float
val cgsm_acre : float
val cgsm_barn : float
val cgsm_liter : float
val cgsm_us_gallon : float
val cgsm_quart : float
val cgsm_pint : float
val cgsm_cup : float
val cgsm_fluid_ounce : float
val cgsm_tablespoon : float
val cgsm_teaspoon : float
val cgsm_canadian_gallon : float
val cgsm_uk_gallon : float
val cgsm_miles_per_hour : float
val cgsm_kilometers_per_hour : float
val cgsm_knot : float
val cgsm_pound_mass : float
val cgsm_ounce_mass : float
val cgsm_ton : float
val cgsm_metric_ton : float
val cgsm_uk_ton : float
val cgsm_troy_ounce : float
val cgsm_carat : float
val cgsm_unified_atomic_mass : float
val cgsm_gram_force : float
val cgsm_pound_force : float
val cgsm_kilopound_force : float
val cgsm_poundal : float
val cgsm_calorie : float
val cgsm_btu : float
val cgsm_therm : float
val cgsm_horsepower : float
val cgsm_bar : float
val cgsm_std_atmosphere : float
val cgsm_torr : float
val cgsm_meter_of_mercury : float
val cgsm_inch_of_mercury : float
val cgsm_inch_of_water : float
val cgsm_psi : float
val cgsm_poise : float
val cgsm_stokes : float
val cgsm_stilb : float
val cgsm_lumen : float
val cgsm_lux : float
val cgsm_phot : float
val cgsm_footcandle : float
val cgsm_lambert : float
val cgsm_footlambert : float
val cgsm_curie : float
val cgsm_roentgen : float
val cgsm_rad : float
val cgsm_solar_mass : float
val cgsm_bohr_radius : float
val cgsm_newton : float
val cgsm_dyne : float
val cgsm_joule : float
val cgsm_erg : float
val cgsm_stefan_boltzmann_constant : float
val cgsm_thomson_cross_section : float
val cgsm_bohr_magneton : float
val cgsm_nuclear_magneton : float
val cgsm_electron_magnetic_moment : float
val cgsm_proton_magnetic_moment : float
val cgsm_faraday : float
val cgsm_electron_charge : float
val mksa_speed_of_light : float
val mksa_gravitational_constant : float
val mksa_plancks_constant_h : float
val mksa_plancks_constant_hbar : float
val mksa_astronomical_unit : float
val mksa_light_year : float
val mksa_parsec : float
val mksa_grav_accel : float
val mksa_electron_volt : float
val mksa_mass_electron : float
val mksa_mass_muon : float
val mksa_mass_proton : float
val mksa_mass_neutron : float
val mksa_rydberg : float
val mksa_boltzmann : float
val mksa_molar_gas : float
val mksa_standard_gas_volume : float
val mksa_minute : float
val mksa_hour : float
val mksa_day : float
val mksa_week : float
val mksa_inch : float
val mksa_foot : float
val mksa_yard : float
val mksa_mile : float
val mksa_nautical_mile : float
val mksa_fathom : float
val mksa_mil : float
val mksa_point : float
val mksa_texpoint : float
val mksa_micron : float
val mksa_angstrom : float
val mksa_hectare : float
val mksa_acre : float
val mksa_barn : float
val mksa_liter : float
val mksa_us_gallon : float
val mksa_quart : float
val mksa_pint : float
val mksa_cup : float
val mksa_fluid_ounce : float
val mksa_tablespoon : float
val mksa_teaspoon : float
val mksa_canadian_gallon : float
val mksa_uk_gallon : float
val mksa_miles_per_hour : float
val mksa_kilometers_per_hour : float
val mksa_knot : float
val mksa_pound_mass : float
val mksa_ounce_mass : float
val mksa_ton : float
val mksa_metric_ton : float
val mksa_uk_ton : float
val mksa_troy_ounce : float
val mksa_carat : float
val mksa_unified_atomic_mass : float
val mksa_gram_force : float
val mksa_pound_force : float
val mksa_kilopound_force : float
val mksa_poundal : float
val mksa_calorie : float
val mksa_btu : float
val mksa_therm : float
val mksa_horsepower : float
val mksa_bar : float
val mksa_std_atmosphere : float
val mksa_torr : float
val mksa_meter_of_mercury : float
val mksa_inch_of_mercury : float
val mksa_inch_of_water : float
val mksa_psi : float
val mksa_poise : float
val mksa_stokes : float
val mksa_stilb : float
val mksa_lumen : float
val mksa_lux : float
val mksa_phot : float
val mksa_footcandle : float
val mksa_lambert : float
val mksa_footlambert : float
val mksa_curie : float
val mksa_roentgen : float
val mksa_rad : float
val mksa_solar_mass : float
val mksa_bohr_radius : float
val mksa_newton : float
val mksa_dyne : float
val mksa_joule : float
val mksa_erg : float
val mksa_stefan_boltzmann_constant : float
val mksa_thomson_cross_section : float
val mksa_bohr_magneton : float
val mksa_nuclear_magneton : float
val mksa_electron_magnetic_moment : float
val mksa_proton_magnetic_moment : float
val mksa_faraday : float
val mksa_electron_charge : float
val mksa_vacuum_permittivity : float
val mksa_vacuum_permeability : float
val mksa_debye : float
val mksa_gauss : float
val num_fine_structure : float
val num_avogadro : float
val num_yotta : float
val num_zetta : float
val num_exa : float
val num_peta : float
val num_tera : float
val num_giga : float
val num_mega : float
val num_kilo : float
val num_milli : float
val num_micro : float
val num_nano : float
val num_pico : float
val num_femto : float
val num_atto : float
val num_zepto : float
val num_yocto : float
